# Form implementation generated from reading ui file 'c:\Users\acerr\OneDrive\Pictures\Screenshots\untukCaslab\Programming\Pythonbasic\teken-4-drone-gcs\DroneLoggingWindow\dlw.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


