# Form implementation generated from reading ui file 'c:\Users\acerr\OneDrive\Pictures\Screenshots\untukCaslab\Programming\Pythonbasic\teken-4-drone-gcs\DroneLoggingWindow\form.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.setEnabled(True)
        Widget.resize(640, 330)
        Widget.setMinimumSize(QtCore.QSize(640, 240))
        Widget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.comboBox = QtWidgets.QComboBox(parent=Widget)
        self.comboBox.setGeometry(QtCore.QRect(20, 50, 221, 31))
        self.comboBox.setObjectName("comboBox")
        self.textEdit = QtWidgets.QTextEdit(parent=Widget)
        self.textEdit.setGeometry(QtCore.QRect(20, 140, 221, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(parent=Widget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 221, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=Widget)
        self.pushButton.setGeometry(QtCore.QRect(20, 175, 221, 29))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(parent=Widget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 231, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Widget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 240, 221, 29))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Widget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 270, 221, 29))
        self.pushButton_3.setObjectName("pushButton_3")
        self.graphicsView_2 = PlotWidget(parent=Widget)
        self.graphicsView_2.setGeometry(QtCore.QRect(260, 20, 361, 291))
        self.graphicsView_2.setObjectName("graphicsView_2")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label_2.setText(_translate("Widget", "Logging Interval (Milliseconds)"))
        self.pushButton.setText(_translate("Widget", "Set Interval"))
        self.label_3.setText(_translate("Widget", "Data Type | Plot of Data -------->"))
        self.pushButton_2.setText(_translate("Widget", "Start Logging"))
        self.pushButton_3.setText(_translate("Widget", "Download Log"))
from pyqtgraph import PlotWidget
