from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QLabel
import csv
import os
import numpy as np

class PidTuningWindowUI(QWidget):
    def __init__(self):
        super().__init__()

        self.resize(1036, 521)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBoxTunning = QtWidgets.QGroupBox(self)
        self.groupBoxTunning.setObjectName("groupBoxTunning")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxTunning)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.groupBoxTunning)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButtonmultirotor = QtWidgets.QPushButton(self.widget)
        self.pushButtonmultirotor.setObjectName("pushButtonmultirotor")
        self.verticalLayout_2.addWidget(self.pushButtonmultirotor)
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabRate = QtWidgets.QWidget()
        self.tabRate.setObjectName("tabRate")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabRate)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widgetRateAll = QtWidgets.QWidget(self.tabRate)
        self.widgetRateAll.setObjectName("widgetRateAll")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetRateAll)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ViewRate = QtWidgets.QWidget(self.widgetRateAll)
        self.ViewRate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ViewRate.setObjectName("ViewRate")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.ViewRate)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.graphRate = QtWidgets.QWidget(self.ViewRate)
        self.graphRate.setObjectName("graphRate")
        self.verticalLayout_10.addWidget(self.graphRate)
        self.scrollbarrate = QtWidgets.QScrollBar(self.ViewRate)
        self.scrollbarrate.setOrientation(QtCore.Qt.Horizontal)
        self.scrollbarrate.setObjectName("scrollbarrate") # Scrollbar untuk Rate Control
        self.scrollbarrate.valueChanged.connect(self.update_graphRate_plot)
        self.verticalLayout_10.addWidget(self.scrollbarrate)
        self.horizontalLayout.addWidget(self.ViewRate)

        # Define grafiknya buat rate
        self.init_graphRate_plot()
        self.graphRate_timer = QtCore.QTimer()
        self.graphRate_timer.timeout.connect(self.update_graphRate_plot)
        self.graphRate_timer.start(1000)
        # dah

        self.widgetfungsirate = QtWidgets.QWidget(self.widgetRateAll)
        self.widgetfungsirate.setObjectName("widgetfungsirate")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widgetfungsirate)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SelectTuningRate = QtWidgets.QWidget(self.widgetfungsirate)
        self.SelectTuningRate.setObjectName("SelectTuningRate")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SelectTuningRate)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.SelectTuningRate)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(self.SelectTuningRate)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.SelectTuningRate)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.SelectTuningRate)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.verticalLayout_5.addWidget(self.SelectTuningRate)
        self.SelectGainRate = QtWidgets.QWidget(self.widgetfungsirate)
        self.SelectGainRate.setObjectName("SelectGainRate")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.SelectGainRate)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.SelectGainRate)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.PropotionalRateBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate)
        self.PropotionalRateBox.setObjectName("PropotionalRateBox")
        self.Kp_Rate = 1.0  # Nilai awal Kp agar tidak error saat update grafik

        self.verticalLayout_4.addWidget(self.PropotionalRateBox)
        self.label_3 = QtWidgets.QLabel(self.SelectGainRate)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.IntegralRateBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate)
        self.IntegralRateBox.setObjectName("IntegralRateBox")
        self.Ki_Rate = 0.1  # Nilai awal Ki agar tidak error saat update grafik

        self.verticalLayout_4.addWidget(self.IntegralRateBox)
        self.label_4 = QtWidgets.QLabel(self.SelectGainRate)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.DerivatifRateBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate)
        self.DerivatifRateBox.setObjectName("DerivatifRateBox")
        self.Kd_Rate = 0.01  # Nilai awal Kd agar tidak error saat update grafik

        self.verticalLayout_4.addWidget(self.DerivatifRateBox)
        self.verticalLayout_5.addWidget(self.SelectGainRate)
        self.ButtonRate = QtWidgets.QWidget(self.widgetfungsirate)
        self.ButtonRate.setObjectName("ButtonRate")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ButtonRate)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ButtonPause_Rate = QtWidgets.QPushButton(self.ButtonRate)
        self.ButtonPause_Rate.setObjectName("ButtonPause_Rate")
        self.horizontalLayout_4.addWidget(self.ButtonPause_Rate)
        self.ButtonPause_Rate.clicked.connect(self.pause_graphrate)

        self.ButtonContinue_Rate = QtWidgets.QPushButton(self.ButtonRate)
        self.ButtonContinue_Rate.setObjectName("ButtonContinue_Rate")
        self.horizontalLayout_4.addWidget(self.ButtonContinue_Rate)
        self.ButtonContinue_Rate.clicked.connect(self.continue_graphrate)

        self.ButtonAuto_Rate = QtWidgets.QPushButton(self.ButtonRate)
        self.ButtonAuto_Rate.setObjectName("ButtonAuto_Rate")
        self.horizontalLayout_4.addWidget(self.ButtonAuto_Rate)
        self.ButtonAuto_Rate.clicked.connect(self.auto_gain1)

        self.ButtonSubmit_Rate = QtWidgets.QPushButton(self.ButtonRate)
        self.ButtonSubmit_Rate.setObjectName("ButtonSubmit_Rate")
        self.ButtonSubmit_Rate.clicked.connect(self.save_gain1)  # Buat submit gain di Rate Control
        
        self.horizontalLayout_4.addWidget(self.ButtonSubmit_Rate)
        self.verticalLayout_5.addWidget(self.ButtonRate)
        self.horizontalLayout.addWidget(self.widgetfungsirate)
        self.verticalLayout_7.addWidget(self.widgetRateAll)
        self.buangan1 = QtWidgets.QWidget(self.tabRate)
        self.buangan1.setObjectName("buangan1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.buangan1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_7.addWidget(self.buangan1)
        self.tabWidget.addTab(self.tabRate, "")
        self.tabAtt = QtWidgets.QWidget()
        self.tabAtt.setObjectName("tabAtt")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabAtt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetAttAll = QtWidgets.QWidget(self.tabAtt)
        self.widgetAttAll.setObjectName("widgetAttAll")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widgetAttAll)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ViewAtt = QtWidgets.QWidget(self.widgetAttAll)
        self.ViewAtt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ViewAtt.setObjectName("ViewAtt")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.ViewAtt)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.graphAtt = QtWidgets.QWidget(self.ViewAtt)
        self.graphAtt.setObjectName("graphAtt")
        self.verticalLayout_17.addWidget(self.graphAtt)
        self.scrollbarAtt = QtWidgets.QScrollBar(self.ViewAtt)
        self.scrollbarAtt.setOrientation(QtCore.Qt.Horizontal)
        self.scrollbarAtt.setObjectName("scrollbarAtt") 
        self.verticalLayout_17.addWidget(self.scrollbarAtt)
        self.horizontalLayout_6.addWidget(self.ViewAtt)
        self.widgetfungsiAtt = QtWidgets.QWidget(self.widgetAttAll)
        self.widgetfungsiAtt.setObjectName("widgetfungsiAtt")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widgetfungsiAtt)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.SelectTuningAttitude = QtWidgets.QWidget(self.widgetfungsiAtt)
        self.SelectTuningAttitude.setObjectName("SelectTuningAttitude")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.SelectTuningAttitude)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.SelectTuningAttitude)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.radioButton_7 = QtWidgets.QRadioButton(self.SelectTuningAttitude)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_9.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.SelectTuningAttitude)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_9.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.SelectTuningAttitude)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_9.addWidget(self.radioButton_9)
        self.verticalLayout_9.addWidget(self.SelectTuningAttitude)
        self.SelectGainRate_4 = QtWidgets.QWidget(self.widgetfungsiAtt)
        self.SelectGainRate_4.setObjectName("SelectGainRate_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.SelectGainRate_4)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.SelectGainRate_4)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.PropotionalAttitudeBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate_4)
        self.PropotionalAttitudeBox.setObjectName("PropotionalAttitudeBox")
        self.verticalLayout_15.addWidget(self.PropotionalAttitudeBox)
        self.label_13 = QtWidgets.QLabel(self.SelectGainRate_4)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_15.addWidget(self.label_13)
        self.IntegralAttitudeBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate_4)
        self.IntegralAttitudeBox.setObjectName("IntegralAttitudeBox")
        self.verticalLayout_15.addWidget(self.IntegralAttitudeBox)
        self.label_14 = QtWidgets.QLabel(self.SelectGainRate_4)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_15.addWidget(self.label_14)
        self.DerivatifAttitudeBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate_4)
        self.DerivatifAttitudeBox.setObjectName("DerivatifAttitudeBox")
        self.verticalLayout_15.addWidget(self.DerivatifAttitudeBox)
        self.verticalLayout_9.addWidget(self.SelectGainRate_4)
        self.ButtonAttitude = QtWidgets.QWidget(self.widgetfungsiAtt)
        self.ButtonAttitude.setObjectName("ButtonAttitude")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.ButtonAttitude)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ButtonPause_Attitude = QtWidgets.QPushButton(self.ButtonAttitude)
        self.ButtonPause_Attitude.setObjectName("ButtonPause_Attitude")
        self.horizontalLayout_14.addWidget(self.ButtonPause_Attitude)
        self.ButtonContinue_Attitude = QtWidgets.QPushButton(self.ButtonAttitude)
        self.ButtonContinue_Attitude.setObjectName("ButtonContinue_Attitude")
        self.horizontalLayout_14.addWidget(self.ButtonContinue_Attitude)
        self.ButtonAuto_Attitude = QtWidgets.QPushButton(self.ButtonAttitude)
        self.ButtonAuto_Attitude.setObjectName("ButtonAuto_Attitude")
        self.horizontalLayout_14.addWidget(self.ButtonAuto_Attitude)
        self.ButtonSubmit_Attitude = QtWidgets.QPushButton(self.ButtonAttitude)
        self.ButtonSubmit_Attitude.setObjectName("ButtonSubmit_Attitude")
        self.horizontalLayout_14.addWidget(self.ButtonSubmit_Attitude)
        self.verticalLayout_9.addWidget(self.ButtonAttitude)
        self.horizontalLayout_6.addWidget(self.widgetfungsiAtt)
        self.verticalLayout.addWidget(self.widgetAttAll)
        self.buangan2 = QtWidgets.QWidget(self.tabAtt)
        self.buangan2.setObjectName("buangan2")
        self.verticalLayout.addWidget(self.buangan2)
        self.tabWidget.addTab(self.tabAtt, "")
        self.tabVelo = QtWidgets.QWidget()
        self.tabVelo.setObjectName("tabVelo")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tabVelo)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widgetVeloAll = QtWidgets.QWidget(self.tabVelo)
        self.widgetVeloAll.setObjectName("widgetVeloAll")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widgetVeloAll)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ViewVelo = QtWidgets.QWidget(self.widgetVeloAll)
        self.ViewVelo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ViewVelo.setObjectName("ViewVelo")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.ViewVelo)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.graphVelo = QtWidgets.QWidget(self.ViewVelo)
        self.graphVelo.setObjectName("graphVelo")
        self.verticalLayout_18.addWidget(self.graphVelo)
        self.scrollbarVelo = QtWidgets.QScrollBar(self.ViewVelo)
        self.scrollbarVelo.setOrientation(QtCore.Qt.Horizontal)
        self.scrollbarVelo.setObjectName("scrollbarVelo")
        self.verticalLayout_18.addWidget(self.scrollbarVelo)
        self.horizontalLayout_3.addWidget(self.ViewVelo)
        self.widgetfungsiVelo = QtWidgets.QWidget(self.widgetVeloAll)
        self.widgetfungsiVelo.setObjectName("widgetfungsiVelo")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widgetfungsiVelo)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.SelectTuningVelocity = QtWidgets.QWidget(self.widgetfungsiVelo)
        self.SelectTuningVelocity.setObjectName("SelectTuningVelocity")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.SelectTuningVelocity)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.SelectTuningVelocity)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.radioButton_12 = QtWidgets.QRadioButton(self.SelectTuningVelocity)
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_12.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.SelectTuningVelocity)
        self.radioButton_13.setObjectName("radioButton_13")
        self.horizontalLayout_12.addWidget(self.radioButton_13)
        self.verticalLayout_13.addWidget(self.SelectTuningVelocity)
        self.SelectGainRate_5 = QtWidgets.QWidget(self.widgetfungsiVelo)
        self.SelectGainRate_5.setObjectName("SelectGainRate_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.SelectGainRate_5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_18 = QtWidgets.QLabel(self.SelectGainRate_5)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_16.addWidget(self.label_18)
        self.PropotionalVelocityBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate_5)
        self.PropotionalVelocityBox.setObjectName("PropotionalVelocityBox")
        self.verticalLayout_16.addWidget(self.PropotionalVelocityBox)
        self.label_21 = QtWidgets.QLabel(self.SelectGainRate_5)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_16.addWidget(self.label_21)
        self.IntegralVelocityBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate_5)
        self.IntegralVelocityBox.setObjectName("IntegralVelocityBox")
        self.verticalLayout_16.addWidget(self.IntegralVelocityBox)
        self.label_22 = QtWidgets.QLabel(self.SelectGainRate_5)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_16.addWidget(self.label_22)
        self.DerivatifVelocityBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate_5)
        self.DerivatifVelocityBox.setObjectName("DerivatifVelocityBox")
        self.verticalLayout_16.addWidget(self.DerivatifVelocityBox)
        self.verticalLayout_13.addWidget(self.SelectGainRate_5)
        self.ButtonVelocity = QtWidgets.QWidget(self.widgetfungsiVelo)
        self.ButtonVelocity.setObjectName("ButtonVelocity")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.ButtonVelocity)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.ButtonPause_Velocity = QtWidgets.QPushButton(self.ButtonVelocity)
        self.ButtonPause_Velocity.setObjectName("ButtonPause_Velocity")
        self.horizontalLayout_15.addWidget(self.ButtonPause_Velocity)
        self.ButtonContinue_Velocity = QtWidgets.QPushButton(self.ButtonVelocity)
        self.ButtonContinue_Velocity.setObjectName("ButtonContinue_Velocity")
        self.horizontalLayout_15.addWidget(self.ButtonContinue_Velocity)
        self.ButtonAuto_Velocity = QtWidgets.QPushButton(self.ButtonVelocity)
        self.ButtonAuto_Velocity.setObjectName("ButtonAuto_Velocity")
        self.horizontalLayout_15.addWidget(self.ButtonAuto_Velocity)
        self.ButtonSubmit_Velocity = QtWidgets.QPushButton(self.ButtonVelocity)
        self.ButtonSubmit_Velocity.setObjectName("ButtonSubmit_Velocity")
        self.horizontalLayout_15.addWidget(self.ButtonSubmit_Velocity)
        self.verticalLayout_13.addWidget(self.ButtonVelocity)
        self.horizontalLayout_3.addWidget(self.widgetfungsiVelo)
        self.verticalLayout_11.addWidget(self.widgetVeloAll)
        self.buangan3 = QtWidgets.QWidget(self.tabVelo)
        self.buangan3.setObjectName("buangan3")
        self.verticalLayout_11.addWidget(self.buangan3)
        self.tabWidget.addTab(self.tabVelo, "")
        self.tabPosi = QtWidgets.QWidget()
        self.tabPosi.setObjectName("tabPosi")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tabPosi)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widgetPosiAll = QtWidgets.QWidget(self.tabPosi)
        self.widgetPosiAll.setObjectName("widgetPosiAll")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widgetPosiAll)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ViewPosi = QtWidgets.QWidget(self.widgetPosiAll)
        self.ViewPosi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ViewPosi.setObjectName("ViewPosi")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.ViewPosi)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.graphPosi = QtWidgets.QWidget(self.ViewPosi)
        self.graphPosi.setObjectName("graphPosi")
        self.verticalLayout_14.addWidget(self.graphPosi)
        self.scrollbarPosi = QtWidgets.QScrollBar(self.ViewPosi)
        self.scrollbarPosi.setOrientation(QtCore.Qt.Horizontal)
        self.scrollbarPosi.setObjectName("scrollbarPosi")
        self.verticalLayout_14.addWidget(self.scrollbarPosi)
        self.horizontalLayout_5.addWidget(self.ViewPosi)
        self.widgetfungsiPosi = QtWidgets.QWidget(self.widgetPosiAll)
        self.widgetfungsiPosi.setObjectName("widgetfungsiPosi")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widgetfungsiPosi)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.SelectTuningRate_3 = QtWidgets.QWidget(self.widgetfungsiPosi)
        self.SelectTuningRate_3.setObjectName("SelectTuningRate_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.SelectTuningRate_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.SelectTuningRate_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.radioButton_4 = QtWidgets.QRadioButton(self.SelectTuningRate_3)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_7.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.SelectTuningRate_3)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_7.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.SelectTuningRate_3)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_7.addWidget(self.radioButton_6)
        self.verticalLayout_6.addWidget(self.SelectTuningRate_3)
        self.SelectGainRate_2 = QtWidgets.QWidget(self.widgetfungsiPosi)
        self.SelectGainRate_2.setObjectName("SelectGainRate_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.SelectGainRate_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.SelectGainRate_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.PropotionalPositionBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate_2)
        self.PropotionalPositionBox.setObjectName("PropotionalPositionBox")
        self.verticalLayout_8.addWidget(self.PropotionalPositionBox)
        self.label_7 = QtWidgets.QLabel(self.SelectGainRate_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.IntegralPositionBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate_2)
        self.IntegralPositionBox.setObjectName("IntegralPositionBox")
        self.verticalLayout_8.addWidget(self.IntegralPositionBox)
        self.label_8 = QtWidgets.QLabel(self.SelectGainRate_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.DerivatifPositionBox = QtWidgets.QDoubleSpinBox(self.SelectGainRate_2)
        self.DerivatifPositionBox.setObjectName("DerivatifPositionBox")
        self.verticalLayout_8.addWidget(self.DerivatifPositionBox)
        self.verticalLayout_6.addWidget(self.SelectGainRate_2)
        self.ButtonPosition = QtWidgets.QWidget(self.widgetfungsiPosi)
        self.ButtonPosition.setObjectName("ButtonPosition")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.ButtonPosition)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ButtonPause_Position = QtWidgets.QPushButton(self.ButtonPosition)
        self.ButtonPause_Position.setObjectName("ButtonPause_Position")
        self.horizontalLayout_10.addWidget(self.ButtonPause_Position)
        self.ButtonContinue_Position = QtWidgets.QPushButton(self.ButtonPosition)
        self.ButtonContinue_Position.setObjectName("ButtonContinue_Position")
        self.horizontalLayout_10.addWidget(self.ButtonContinue_Position)
        self.ButtonAuto_Position = QtWidgets.QPushButton(self.ButtonPosition)
        self.ButtonAuto_Position.setObjectName("ButtonAuto_Position")
        self.horizontalLayout_10.addWidget(self.ButtonAuto_Position)
        self.ButtonSubmit_Position = QtWidgets.QPushButton(self.ButtonPosition)
        self.ButtonSubmit_Position.setObjectName("ButtonSubmit_Position")
        self.horizontalLayout_10.addWidget(self.ButtonSubmit_Position)
        self.verticalLayout_6.addWidget(self.ButtonPosition)
        self.horizontalLayout_5.addWidget(self.widgetfungsiPosi)
        self.verticalLayout_19.addWidget(self.widgetPosiAll)
        self.buangan4 = QtWidgets.QWidget(self.tabPosi)
        self.buangan4.setObjectName("buangan4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.buangan4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_19.addWidget(self.buangan4)
        self.tabWidget.addTab(self.tabPosi, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_3.addWidget(self.widget)
        self.verticalLayout_12.addWidget(self.groupBoxTunning)

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(0)
    
    def auto_gain1(self):
        # Simulasi otomatisasi pengaturan gain
        self.PropotionalRateBox.setValue(1.0)
        self.IntegralRateBox.setValue(0.1)
        self.DerivatifRateBox.setValue(0.01)
        print("Auto-tuned Rate Gains: Kp=1.0, Ki=0.1, Kd=0.01")
    
    def save_gain1(self):
        # Simpan nilai Kp, Ki, Kd untuk Rate Controller
        self.Kp_Rate = self.PropotionalRateBox.value()
        self.Ki_Rate = self.IntegralRateBox.value()
        self.Kd_Rate = self.DerivatifRateBox.value()
        print(f"Saved Rate Gains: Kp={self.Kp_Rate}, Ki={self.Ki_Rate}, Kd={self.Kd_Rate}")
    
    def init_graphRate_plot(self):
        # Membuat Figure dan Canvas
        self.graphRate_fig = Figure(figsize=(1, 2), dpi=100)
        self.graphRate_ax = self.graphRate_fig.add_subplot(111)
        self.graphRate_ax.set_title("graphRate Live")
        self.graphRate_ax.set_xlabel("Detik")
        self.graphRate_ax.set_ylabel("Value")
        self.graphRate_ax.grid(True)
        self.graphRate_canvas = FigureCanvas(self.graphRate_fig)
        layout = QtWidgets.QVBoxLayout(self.graphRate)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(self.graphRate_canvas)

    def pause_graphrate(self):
        self.graphRate_timer.stop()

    def continue_graphrate(self):
        self.graphRate_timer.start(1000)

    def update_graphRate_plot(self):
        # Baca data dari log.csv
        detik = []
        value = []
        value_ubah = []
        window_size = 10 
        
        if os.path.exists("log.csv"):
            with open("log.csv", "r") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    try:
                        detik.append(int(row["detik"])) # ini x nya dalam detik
                        value.append(float(row["value"])) # ini y nya buat masukin fungsi nyaa
                        value_ubah.append(float(row["value"]) * ( self.Kp_Rate + self.Ki_Rate + self.Kd_Rate) ) # ubah 
                    except Exception:
                        continue
        # Update scrollbar maximum sesuai jumlah data
        if len(detik) > window_size:
            self.scrollbarrate.setMaximum(len(detik) - window_size)
        else:
            self.scrollbarrate.setMaximum(0)
            self.scrollbarrate.setValue(0)

        # Ambil window data sesuai posisi scrollbar
        start_idx = self.scrollbarrate.value()
        end_idx = start_idx + window_size
        detik_window = detik[start_idx:end_idx]
        value_window = value[start_idx:end_idx]
        value_ubah_window = value_ubah[start_idx:end_idx]

        self.graphRate_ax.clear()
        self.graphRate_ax.set_title("graphRate Live")
        self.graphRate_ax.set_xlabel("Detik")
        self.graphRate_ax.set_ylabel("Value")
        self.graphRate_ax.grid(True)
        if detik_window and value_window:
            self.graphRate_ax.plot(detik_window, value_window, color='g')
            self.graphRate_ax.plot(detik_window, value_ubah_window, color='r')
            self.graphRate_ax.legend(["Value", "Value Ubah"])
        self.graphRate_canvas.draw()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "PID Tuning"))
        self.groupBoxTunning.setTitle(_translate("Form", "Tuning"))
        self.pushButtonmultirotor.setText(_translate("Form", "MultiRotor"))
        self.tabWidget.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("Form", "Select Tuning :"))
        self.radioButton.setText(_translate("Form", "Roll"))
        self.radioButton_2.setText(_translate("Form", "Pitch"))
        self.radioButton_3.setText(_translate("Form", "Yaw"))
        self.label_2.setText(_translate("Form", "P"))
        self.label_3.setText(_translate("Form", "I"))
        self.label_4.setText(_translate("Form", "D"))
        self.ButtonPause_Rate.setText(_translate("Form", "Pause"))
        self.ButtonContinue_Rate.setText(_translate("Form", "Continue"))
        self.ButtonAuto_Rate.setText(_translate("Form", "Auto"))
        self.ButtonSubmit_Rate.setText(_translate("Form", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRate), _translate("Form", "Rate Controller"))
        self.label_11.setText(_translate("Form", "Select Tuning :"))
        self.radioButton_7.setText(_translate("Form", "Roll"))
        self.radioButton_8.setText(_translate("Form", "Pitch"))
        self.radioButton_9.setText(_translate("Form", "Yaw"))
        self.label_12.setText(_translate("Form", "P"))
        self.label_13.setText(_translate("Form", "I"))
        self.label_14.setText(_translate("Form", "D"))
        self.ButtonPause_Attitude.setText(_translate("Form", "Pause"))
        self.ButtonContinue_Attitude.setText(_translate("Form", "Continue"))
        self.ButtonAuto_Attitude.setText(_translate("Form", "Auto"))
        self.ButtonSubmit_Attitude.setText(_translate("Form", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAtt), _translate("Form", "Attitude Controller"))
        self.label_15.setText(_translate("Form", "Select Tuning :"))
        self.radioButton_12.setText(_translate("Form", "Horizontal"))
        self.radioButton_13.setText(_translate("Form", "Vertical"))
        self.label_18.setText(_translate("Form", "P"))
        self.label_21.setText(_translate("Form", "I"))
        self.label_22.setText(_translate("Form", "D"))
        self.ButtonPause_Velocity.setText(_translate("Form", "Pause"))
        self.ButtonContinue_Velocity.setText(_translate("Form", "Continue"))
        self.ButtonAuto_Velocity.setText(_translate("Form", "Auto"))
        self.ButtonSubmit_Velocity.setText(_translate("Form", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVelo), _translate("Form", "Velocity Controller"))
        self.label_5.setText(_translate("Form", "Select Tuning :"))
        self.radioButton_4.setText(_translate("Form", "Roll"))
        self.radioButton_5.setText(_translate("Form", "Pitch"))
        self.radioButton_6.setText(_translate("Form", "Yaw"))
        self.label_6.setText(_translate("Form", "P"))
        self.label_7.setText(_translate("Form", "I"))
        self.label_8.setText(_translate("Form", "D"))
        self.ButtonPause_Position.setText(_translate("Form", "Pause"))
        self.ButtonContinue_Position.setText(_translate("Form", "Continue"))
        self.ButtonAuto_Position.setText(_translate("Form", "Auto"))
        self.ButtonSubmit_Position.setText(_translate("Form", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPosi), _translate("Form", "Position Controller"))

